language: go
branches:
  only:
  - master
go:
  - tip
script:
  - ./control.sh build
deploy:
  provider: releases
  api_key:
    secure: ...
  file:
    - ruready
    - ruready.sha1
  skip_cleanup: true
  on:
    repo: duguying/blog
    tags: true